### ISSUE TITLE
All slabs are breakable by hand

### ISSUE THREAD

**Issue by VivianTheFox** [LO6AN/New-Frontier-Craft#10]
Honestly I don't know how we missed this one, but yeah. Every slab in the game can be broken by hand, and it will drop itself. 
This bug has existed since NFC 1.8.6

**Comment by Roadhog360** [comment]
Zowja has told me this is intended with the logic that slabs would be easier to move by hand. He intentionally added that. Back when 1.8.6 first came out I found it pretty fast and that's what he told me.

Close with Works as Intended label or consider it a bug and label this accordingly?
