### ISSUE TITLE
Better Than Wolves, unable to be with NFC3.4.2

### ISSUE THREAD

**Issue by KIKI-2007** [LO6AN/New-Frontier-Craft#101]

**Comment by VivianTheFox** [comment]
Better Than Wolves hasn't been updated for v3.4.2 yet, and I don't plan to update it as I want to wait to put my effort into getting the more fully featured build v2.94 working with our next NFC release, v3.5.0

**Comment by germe-deb** [comment]
how do you install better than wolves in NFC?
