### ISSUE TITLE
Headwear doesn't change its position with the player while crouching

### ISSUE THREAD

**Issue by Pomi108** [LO6AN/New-Frontier-Craft#12]
See the title and attached screenshots.
![2021-05-02_19 50 02](https://user-images.githubusercontent.com/59484948/116822557-ca68e380-ab7f-11eb-9937-edd27760be6f.png)
![2021-05-02_19 50 05](https://user-images.githubusercontent.com/59484948/116822561-cdfc6a80-ab7f-11eb-9260-5b676e17c4dc.png)

**Comment by Roadhog360** [comment]
Fixed in future snapshot
