### ISSUE TITLE
Quitting the game from the main menu button causes 'Not responding...'

### ISSUE THREAD

**Issue by toontownlpz** [LO6AN/New-Frontier-Craft#17]
Title says all.

**Comment by Roadhog360** [comment]
Mods installed?

**Comment by toontownlpz** [comment]
Nope, plain vanilla using whatever built-in Java the launcher provides for it. I'll try to see if there's a specific set of instructions to make it happen.

**Comment by Roadhog360** [comment]
Any updates?

**Comment by Roadhog360** [comment]
Might also be worth telling us stuff like graphics cards, CPU, and other stuff that could externally affect the game.
