### ISSUE TITLE
Flicking through GUI Scale seems to trigger an update to the Smooth Tree Lighting setting

### ISSUE THREAD

**Issue by toontownlpz** [LO6AN/New-Frontier-Craft#18]
This is inconsistent, it seems. It seems when flicking through GUI Scale the Smooth Tree Lighting toggles sometimes changes. I've noticed this seems to mostly occur around Large or Auto.

**Comment by VivianTheFox** [comment]
In the process of rebuilding and cleaning up the Video Settings for v3.5, splitting the options based on whether they configure the screen or world rendering into Visual Settings and Screen Settings, the bug was patched
