### ISSUE TITLE
portals are invisible

### ISSUE THREAD

**Issue by Raidenplays** [LO6AN/New-Frontier-Craft#22]
<img width="1680" alt="Screen Shot 2021-06-13 at 4 00 29 PM" src="https://user-images.githubusercontent.com/69190946/121824406-e4a6de80-cc60-11eb-8e61-b11115cb5d3c.png">

**Comment by Roadhog360** [comment]
Are there any mods installed?

**Comment by Roadhog360** [comment]
Caused by mods
