### ISSUE TITLE
telescope doesn't zoom

### ISSUE THREAD

**Issue by Raidenplays** [LO6AN/New-Frontier-Craft#23]
it just adds the border without zooming in

<img width="1680" alt="Screen Shot 2021-06-13 at 4 02 33 PM" src="https://user-images.githubusercontent.com/69190946/121824458-28014d00-cc61-11eb-9d42-c1c22b57b939.png">
<img width="1680" alt="Screen Shot 2021-06-13 at 4 02 35 PM" src="https://user-images.githubusercontent.com/69190946/121824463-2cc60100-cc61-11eb-803f-6c6bd3e9362c.png">

**Comment by Roadhog360** [comment]
Are there any mods installed?

**Comment by Roadhog360** [comment]
Caused by mods
