### ISSUE TITLE
everything that has 1 layer of pixels are actually pretty pixxely

### ISSUE THREAD

**Issue by ghost** [LO6AN/New-Frontier-Craft#26]
![8e71566fcef0e74aa2002475d65f32ec](https://user-images.githubusercontent.com/67587410/121914988-11c3c180-cd33-11eb-818f-4e70a93ea8e0.png)

**Comment by ghost** [comment]
forgot to add that this is also caused by Betatweaks

**Comment by Roadhog360** [comment]
Issues relating to add-ons should be fixed on the add-on's end in most cases.
