### ISSUE TITLE
Trello bugs master list.

### ISSUE THREAD

**Issue by Roadhog360** [LO6AN/New-Frontier-Craft#28]
A private copy of the Trello has been made, but to avoid managing the same bugs from two different places at the same time we're moving them all to GitHub under this one master-list.

Some bugs have been considered more fit as ideas and moved to our dev Trello. Others have been combined if they're considered directly related.

1: Maps are hardly ever new and often just break and become map_0 (Server)
2: Fix issue where trying to use items/attack/click entities through blocks without a full hitbox doesn't work (High Priority, Server)
~~3: Looking at a mob in the Nether with F3 enabled can sometimes cause the world to render with opacity (High Priority, Client)~~
4: All slabs have the material of stone. (Client, Server) (This can really only be fixed when the major ID rewrite happens.)
5: Sometimes sitting dogs can appear as standing on a server (Client, Server) (Packet info might need to be tweaked, hence the "Client" label here)
6: Seeds between server and client are mostly aligned, but some things like ore placement and world decorators are slightly off (Client, Server) (Possible WAI)
7: Item names appear behind other UI elements (Low Priority, Client)

**Comment by Roadhog360** [comment]
Trello 3 might have been caused by the lag-o-meter as I can't get it to reproduce.

**Comment by VivianTheFox** [comment]
This issue should probably be subdivided into individual issues, that way we can individually comment on and close them when resolved. Also, way easier to spot in a list a bug when scrolling through what needs to be fixed than (Bugs Master List)

**Comment by VivianTheFox** [comment]
Trello 4 will be fixed in v3.5 due to us splitting the wood slab off into its own block. Rest are closed due to them being moved to separate issues.
Trello 1: #84 
Trello 2: #85 
Trello 5: #86 
Trello 6: #87 
Trello 7: #88

**Comment by Roadhog360** [comment]
Wood slab being its own block is ill advised; would mean the "stone" version becomes unobtainable, making it petrified would change all stone slabs in the world.

Suggestion is to instead add the petrified slab to the slabs list and add the "stone wood" slab to the axes effective list using Forge's metadata-specific harvest levels.
