### ISSUE TITLE
Tool Durability Inconsistency between Client and Server

### ISSUE THREAD

**Issue by VivianTheFox** [LO6AN/New-Frontier-Craft#30]
Server thinks the tool is broken one block earlier than it actually is, causing the last block you mine to vanish into thin air if it's not something that can be broken by your hands. Stats are known to be the same between the two, and original issue was resolved on the client side, so this can probably be resolved by either fixing the inconsistency between the two (the ideal solution), or boosting the durability of the tools on the server side by 1 (the bodgy solution).

**Comment by Roadhog360** [comment]
No, this is the same issue where the block drop is calculated after you destroy it.

**Comment by Roadhog360** [comment]
GitHub, I didn't click "close with comment", why did you do that.

**Comment by Roadhog360** [comment]
Maybe GitHub made the right call because I just found a fix.
