### ISSUE TITLE
In-Game Tooltip redraws every time the durability on a tool updates.

### ISSUE THREAD

**Issue by VivianTheFox** [LO6AN/New-Frontier-Craft#31]
Fix is just by making it not respond to the metadata values for tools or other things that'll be updating their metadata value as you hold them

**Comment by Roadhog360** [comment]
Two possible fixes, either make it so if the meta changes but your slot didn't, don't redraw the tooltip, or two, make it so the durability is displayed when holding a tool.

**Comment by Roadhog360** [comment]
Made the latter as a solution since the solutions I can think of to make the former are way too funky. Check out your DMs and close this if you like the solution.

**Comment by Roadhog360** [comment]
Ok, durability is considered a different option for a different day, fixed it normally.
