### ISSUE TITLE
Wonky Held Block Lighting in Inventory During Blood Moon

### ISSUE THREAD

**Issue by VivianTheFox** [LO6AN/New-Frontier-Craft#53]
![2021-06-24_00 59 16](https://user-images.githubusercontent.com/19847740/123210367-801d2800-d487-11eb-8020-80812432179e.png)
Top face of block doesn't have the lighting match the other faces of the block. Possible fixes are either making it so the blood moon tesselator code has no effect on things held in the inventory, or find some fix to the issue itself.

**Comment by Roadhog360** [comment]
Solution would be to disable the blood moon lighting on the player model in the inventory, or making it slightly darker because the top face is the brightest, too bright to render with color, and also rendering the player model with the tint. What do you think?

**Comment by VivianTheFox** [comment]
The former of the two would be easier, and would mesh well with the interface not really being changed much by the external environment. I'd go with just disabling blood moon lighting in the inventory screen.
