### ISSUE TITLE
Chinese characters (Unicode font) support

### ISSUE THREAD

**Issue by moechakucha** [LO6AN/New-Frontier-Craft#70]
I was trying to translate the game to Simplified Chinese, but soon I found that the Chinese characters did not show up in the game.

Could you please add Chinese characters (using unicode font) support?

Sorry for poor English.

**Comment by Roadhog360** [comment]
Unfortunately this will not be possible from our and as there are thousands of Chinese characters and each one will be have to mapped by hand.

Unless a better font system is added I don't think any developer on our team will have the time to individually map and test thousands of characters. However if you manage to get them all in, you are free to submit a pull request.

**Comment by Roadhog360** [comment]
Also closing because this is a suggestion. You are free to join our server and post this again there.
