### ISSUE TITLE
Outer Layer Skin Transparency Non-Functional

### ISSUE THREAD

**Issue by mrnikoffical** [LO6AN/New-Frontier-Craft#71]
I made myself a skin the other day and went to New Frontier Craft and here the glasses are incorrectly displayed on the skin  :(
https://cdn.discordapp.com/attachments/646412212507770958/884460740059213844/2021-09-06_18.30.05.png

**Comment by VivianTheFox** [comment]
What's being displayed incorrectly with the glasses? How are they supposed to look? Is the issue with transparency, them rendering in the wrong location, or what?

**Comment by Roadhog360** [comment]
Transparency, the outer hat layers are supposed to have that.

**Comment by mrnikoffical** [comment]
Извени что на русском отвечаю, мне лень переводить! Мои очки на скине имеют прозрачную текстуру Отправлено из приложения "Почта" для Windows От: LoganОтправлено: 13 октября 2021 г. в 4:40Кому: LO6AN/New-Frontier-CraftКопия: mrnikoffical; AuthorТема: Re: [LO6AN/New-Frontier-Craft] Incorrect display of skins (#71) What's being displayed incorrectly with the glasses? How are they supposed to look? Is the issue with transparency, them rendering in the wrong location, or what?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mrnikoffical** [comment]
Я когда играю в New Frontier Craft у меня везде не прозрачная текстура на
скине, хотя она у меня прозрачная...

ср, 13 окт. 2021 г., 4:40 Logan ***@***.***>:
