### ISSUE TITLE
Lead breaks your inventory and deletes items permenantly(server side)

### ISSUE THREAD

**Issue by ghost** [LO6AN/New-Frontier-Craft#74]
(copied from the Discord server)once you place it in your inventory, quit te server so your inventory gets saved 100%, join again and put it in the chest again but by shift-clicking this time, don’t leave the chest and shift click it in your hand so it’s automatically equipped, now leave the chest and just move it around in your inventory, as long as it stays in your inventory, once you open and/or close a chest it and move the lead around, it will go back to his original spot every time, even if you switch it with any item or multiple items, this is dangerous cuz that’s how i lost my pickaxe, it basically errased it by overwriting the data or something.

**Comment by Roadhog360** [comment]
Closing this as stale because no one else has ever experienced it, it can't be reproduced by us and you yourself haven't gotten it to happen.
