### ISSUE TITLE
Compass Coords Overlap Hotbar with Narrow Screen

### ISSUE THREAD

**Issue by VivianTheFox** [LO6AN/New-Frontier-Craft#76]
![2021-12-29_14 11 49](https://user-images.githubusercontent.com/19847740/147699855-02af72f9-65e2-4fb6-89e3-73a2400524d4.png)

**Comment by Roadhog360** [comment]
Hm... I think this could be fixed by displaying the
coords
like
this
and moving the compass on top when the screen is narrow. This might still overlap in the millions but at that point who cares lmao

**Comment by VivianTheFox** [comment]
Sounds good to me, let's do that

**Comment by VivianTheFox** [comment]
Solution I ended up opting for is making it so if the FontRender (in-game) width of the coords string is any longer than where the hotbar starts, the clock and compass get shifted above the hotbar. This should cover every edgecase where the compass coords would overflow over the hotbar
