### ISSUE TITLE
ModLoader + HowManyItems crashes on world start-up

### ISSUE THREAD

**Issue by connorhedgehog** [LO6AN/New-Frontier-Craft#81]
I installed the official NFC versions of ModLoader and HowManyItems, ModLoader as a jar mod and HowManyItems in the mods folder. As soon as I opened my world, the game crashed with this report: https://www.toptal.com/developers/hastebin/dasaruyena.http

**Comment by ghost** [comment]
Hello dear `@robbieradiant`!

Are you sure you have installed the patched version of both ModLoader and HowManyItems? If not, there is a link to the NFC's website with patched versions of mods (v3.4.1):
https://newfrontiercraft.net/thread/165/nfc-v3-4-mods-addons

**Comment by Roadhog360** [comment]
This issue tracker is for bugs in the vanilla game, issues with mods should be talked about in the Discord channel instead.
