### ISSUE TITLE
[Bloodmoon bug] Top of Glowstone isn't tinted red like it should be.

### ISSUE THREAD

**Issue by ghost** [LO6AN/New-Frontier-Craft#82]
![2022-02-10_02 02 27](https://user-images.githubusercontent.com/67587410/153316968-a68dedc6-efe0-4f49-a9bb-87d58c76b25b.png)

**Comment by VivianTheFox** [comment]
This bug is frustrating, but it's just a side-effect of how the rendering system works in the game. We might eventually find a patch for it, and fix it, but otherwise this is going to stay in the game
