### ISSUE TITLE
Duplicate Snowballs

### ISSUE THREAD

**Issue by VivianTheFox** [LO6AN/New-Frontier-Craft#92]
When mining snowballs on the server with a shovel, they spawn two entities, the real one alongside a ghost one. I'm 100% certain this has to do with some of our internal rewrites to make magnet tools a little cleaner internally

**Comment by Roadhog360** [comment]
Ghost entities on the server are a client issue, the client typically creates ghost entities when on a server.

**Comment by VivianTheFox** [comment]
Right, yeah. Label was wrong. But yeah
