### ISSUE TITLE
 Ears (v1.4.5) doesnt work with NFC Modloader (v4.6.1) 

### ISSUE THREAD

**Issue by vskoldr21** [LO6AN/New-Frontier-Craft#93]
Summary
------------------------------
Installing Ears and ModloaderNFC in the same Minecraft instance causes a crash to desktop
[Error Log](https://gist.github.com/LumiEvi/cf0e3ee1c1229d2145582abece2b19a9)
[Ears Issue](https://github.com/unascribed/Ears/issues/105)

Steps to Reproduce
------------------------------
1. Install NFC v3.4.2. (MultiMC or Prism Launcher recommended for these steps, [Installation Instructions](https://newfrontiercraft.net/thread/116/install-new-frontier-craft))

2. Download [Ears](https://github.com/unascribed/Ears/releases/download/v1.4.5/ears-nfc-1.4.5.jar)

3. Move `ears-nfc-1.4.5.jar` to .minecraft folder of NFC Instance.

4. Rename `ears-nfc-1.4.5.jar` to `ears.jar`.

5. Add `-javaagent:ears.jar` to Java Arguments.

6. Download [ModloaderNFC v4.6.1](https://github.com/New-Frontier-Craft/NFC-Addons/raw/main/NFC%2520v3.4.2/Addons/ModLoaderNFC%2520v4.6.1.zip)

7. Install as a jarmod. (MultiMC: Open Instance Edit Window, click `Version`, click `Add to Minecraft.jar`, find `ModLoaderNFC v4.6.1.zip` and click **Open**.)

8. Launch the title.

9. Click on `Singleplayer`.

10. Create a New World, gamemode and seed do not matter.

11. Load into the world.

12. Observe Crash.

Results
------------------------------
Expected Result: Load into the world with both Ears and Modloader working

Actual Result: Title crashes

**Comment by VivianTheFox** [comment]
Fixed with new jarmod version of Ears for v3.4.2 and the merging of Ears into NFC with v3.5
